- name: DNS installation and configuration
  gather_facts: false
  hosts: linux_dns_host
  vars:
    db_forward_file_path: "/etc/bind/db-forward.{{ domain_name }}"
  tasks:
    - name: Install bind9 package
      command: apt install bind9 -y
    - name: Push named configuration file
      template:
        src: templates/named-conf.j2
        dest: /etc/bind/named.conf.local
    - name: Push zone configuration files
      template:
        src: templates/db-forward.j2
        dest: "{{ db_forward_file_path }}"
    - name: Restart bind9 service
      command: systemctl restart named