all:
  vars:
    domain_name: lks.id
    dns_server_list:
      - hostname: win
        ip: 10.23.0.8
      - hostname: lin1
        ip: 10.23.0.16
      - hostname: lin2
        ip: 10.23.0.32
    ha_server_list:
      - 10.23.0.16
      - 10.23.0.32
  hosts:
    LIN1:
      ansible_host: 10.23.0.16
      hostname: "LNX-HOST-01"
      webcolor: "green"
      dns: lin1.lks.id
    LIN2:
      ansible_host: 10.23.0.32
      hostname: "LNX-HOST-02"
      webcolor: "yellow"
      dns: lin2.lks.id
    WIN:
      ansible_host: 10.23.0.8
      hostname: "WIN-HOST-001"
      dns: win.lks.id
      webcolor: "red"
      ansible_user: administrator
      ansible_password: admin@12345
      ansible_port: 5986
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore
      # ansible_winrm_transport: ntlm # ntlm | basic
      # ansible_winrm_scheme: http
  children:
    linux:
      vars:
        ansible_user: root
        ansible_password: root
      hosts:
        LIN1:
        LIN2:
    linux_web_host:
      hosts:
        LIN1:
        LIN2:
    linux_dns_host:
      hosts:
        LIN1:
    linux_ha_host:
      hosts:
        LIN1:
